data_root: /home/oem/datas/jayeon/Dataset/amos22_resize_filtered/
work_dir: /home/oem/datas/jayeon/TrainedData/Paper/Segmenter/

finetune:
  checkpoint: amos_resize_filtered_test_128_b4_2e-3 #amos_128_b4_2.5e-3 #amos_resize_filtered_NonCrop_128_b4_2e-4
  detector:
    in_channels: 1
    out_channels: 1
    embed_dim: 96 
    embedding_dim: 64 #1, 8, 27, 64, 216, (256)
    channels: [ 24, 48, 60 ]
    blocks: [ 1, 2, 3, 2 ]
    heads: [ 1, 2, 4, 4 ]
    r: [ 4, 2, 2, 1 ]
    dropout: 0.3
  slim_unetr:
    in_channels: 1
    out_channels: 1
    embed_dim: 96 
    embedding_dim: 64 #1, 8, 27, 64, 216, (256)
    channels: [ 24, 48, 60 ]
    blocks: [ 1, 2, 3, 2 ]
    heads: [ 1, 2, 4, 4 ]
    r: [ 4, 2, 2, 1 ]
    dropout: 0.3
  data_load_sap: True

trainer:
  num_epochs: 2000
  warmup: 5
  train_ratio: 0.8
  batch_size: 4
  lr: 2e-3 #0.002
  min_lr: 2e-7 #0.0000002 사용되지 않음
  optimizer: adamw
  weight_decay: 0.05
  weight_decay_end: 0.04
  momentum_teacher: 0.996
  pred_ratio_varpytho: 0
  num_workers: 8
  image_size: 128 #192
  save_cycle: 100 #저장 간격
  resume: False

inference:
  epoch: best
  pathseg: train
  #finetune.checkpoint 과 같은 이름의 train folder load

generation:
  epoch: best
  pathseg: train
  #finetune.checkpoint 과 같은 이름의 train folder load